# Generated by Django 5.1.6 on 2025-02-17 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('checked', models.BooleanField(default=False)),
                ('fav', models.BooleanField(default=False)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_toDoList', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reg_date'],
                'indexes': [models.Index(fields=['-reg_date'], name='Toding_todo_reg_dat_7af31a_idx')],
            },
        ),
    ]
